# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='gmaps_iFrame',
            new_name='gmaps_iFrame_src',
        ),
    ]
