# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0002_auto_20160307_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='venue_name',
        ),
    ]
