# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0003_auto_20160307_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='registration_cost',
            new_name='registration_cost_in_pounds',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='student_cost',
            new_name='student_cost_in_pounds',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='registration_cost',
            new_name='registration_cost_in_pounds',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='student_cost',
            new_name='student_cost_in_pounds',
        ),
    ]
