# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0004_auto_20160307_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='testimonials',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
