# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0005_course_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='call_for_papers_programme',
            field=models.FileField(upload_to='PDFs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='brochure',
            field=models.FileField(upload_to='PDFs/'),
        ),
    ]
