# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0006_auto_20160307_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
