# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0008_auto_20160307_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='cfp_programme_bool',
        ),
        migrations.AddField(
            model_name='conference',
            name='call_for_papers_or_programme',
            field=models.CharField(choices=[('Call for papers', 'Call for papers'), ('Programme', 'Programme')], default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='gmaps_iFrame_src',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
