# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0010_remove_course_student_cost_in_pounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
