# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesConferences', '0012_course_who_should_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='main_description',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='slug',
        ),
    ]
