# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('call_for_papers_programme', models.FileField(upload_to='PDFs/')),
                ('call_for_papers_or_programme', models.CharField(choices=[('Call for papers', 'Call for papers'), ('Programme', 'Programme')], max_length=16)),
                ('description', models.CharField(max_length=4000)),
                ('conference_themes', models.CharField(max_length=4000)),
                ('is_partner_conference', models.BooleanField(default=False)),
                ('registration_cost_in_pounds', models.IntegerField(default=0)),
                ('student_cost_in_pounds', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('gmaps_iFrame_src', models.URLField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Venue'),
        ),
    ]
