# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='description',
            new_name='main_description',
        ),
    ]
