# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20160310_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='call_for_papers_or_programme',
            field=models.CharField(blank=True, choices=[('Call for papers', 'Call for papers'), ('Programme', 'Programme')], max_length=16),
        ),
        migrations.AlterField(
            model_name='conference',
            name='call_for_papers_programme',
            field=models.FileField(blank=True, upload_to='PDFs/'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_themes',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='conference',
            name='main_description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='conference',
            name='one_day_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='conference',
            name='registration_cost_in_pounds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='conference',
            name='student_cost_in_pounds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='conference',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
