# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20160310_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='conference_name',
            new_name='event_name',
        ),
    ]
