# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20160310_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
