# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('brochure', models.FileField(upload_to='PDFs/')),
                ('main_description', models.CharField(max_length=4000)),
                ('testimonials', models.CharField(max_length=2000)),
                ('who_should_attend', models.CharField(max_length=2000)),
                ('registration_cost_in_pounds', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('gmaps_iFrame_src', models.URLField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Venue'),
        ),
    ]
