# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='event_name',
        ),
    ]
