# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160310_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='Glasgow', max_length=30),
            preserve_default=False,
        ),
    ]
